name: Content API Docker
on:
  workflow_dispatch:
  push:
    branches: [ main, staging ]
    paths:
      - 'content_api/**'
      - '.github/workflows/content-api-docker.yml'
    tags:
      - 'v*.*.*'

permissions:
  contents: read
  packages: write

jobs:
  build-push-ghcr:
    name: Build & Push (GHCR)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker metadata (GHCR)
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/${{ github.repository_owner }}/content-api
          tags: |
            type=ref,event=branch
            type=ref,event=tag
            type=sha

      - name: Build and push (GHCR)
        uses: docker/build-push-action@v5
        with:
          context: .
          file: content_api/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  build-push-dockerhub:
    name: Build & Push (Docker Hub)
    runs-on: ubuntu-latest
    if: ${{ secrets.DOCKERHUB_USERNAME != '' && secrets.DOCKERHUB_TOKEN != '' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker metadata (Docker Hub)
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ secrets.DOCKERHUB_USERNAME }}/content-api
          tags: |
            type=ref,event=branch
            type=ref,event=tag
            type=sha

      - name: Build and push (Docker Hub)
        uses: docker/build-push-action@v5
        with:
          context: .
          file: content_api/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
