name: Mesh Registry
on:
  workflow_dispatch:
  push:
    paths:
      - 'scripts/gists/generate-mesh-registry.ps1'
      - '**/hydra.manifest.json'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up PowerShell
        uses: PowerShell/PowerShell@v1
        with:
          pwsh-version: '7.4.x'
      - name: Generate mesh registry
        shell: pwsh
        run: |
          ./scripts/gists/generate-mesh-registry.ps1 -RootPath "${{ github.workspace }}" -Output "mesh.registry.json"
      - name: Update secret gist with registry
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN_GIST }}
          MESH_GIST_ID: ${{ secrets.MESH_GIST_ID }}
        run: |
          sudo apt-get update && sudo apt-get install -y jq
          CONTENT=$(jq -Rs . < mesh.registry.json)
          echo "{\"files\": {\"mesh.json\": {\"content\": $CONTENT}}}" > payload.json
          gh api -X PATCH "gists/${MESH_GIST_ID}" --input payload.json
