name: Mesh Registry
on:
  workflow_dispatch:
  schedule:
    - cron: '15 * * * *'  # hourly at :15
  push:
    paths:
      - 'scripts/gists/generate-mesh-registry.ps1'
      - 'repos.txt'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up PowerShell
        uses: PowerShell/PowerShell@v1
        with:
          pwsh-version: '7.4.x'
      - name: Generate mesh registry from repos.txt
        shell: pwsh
        env:
          GH_TOKEN: ${{ secrets.GH_REPO_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GH_REPO_TOKEN }}
        run: |
          ./scripts/gists/generate-mesh-registry.ps1 -ReposFile "${{ github.workspace }}/repos.txt" -Output "mesh.registry.json"
      - name: Update secret gist with registry
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN_GIST }}
          MESH_GIST_ID: ${{ secrets.MESH_GIST_ID }}
        run: |
          sudo apt-get update && sudo apt-get install -y jq
          CONTENT=$(jq -Rs . < mesh.registry.json)
          echo "{\"files\": {\"mesh.json\": {\"content\": $CONTENT}}}" > payload.json
          gh api -X PATCH "gists/${MESH_GIST_ID}" --input payload.json
